function yout = M(x0,t0,t1,Fc,Fs,Fo,Ft,Fb,...
    cw,Hml,K,aml,L,hc,...
    a,b,c,d,...
    Ka,Kb,Kc,Kd)
%M Summary of this function goes here
%   Detailed explanation goes here
[~,y,~,~,~,~]=disode45(@(t,y) diff_eqs_param(t,y,...
    Fc,Fs,Fo,Ft,Fb,...
    cw,Hml,K,aml,L,hc,...
    a,b,c,d,...
    Ka,Kb,Kc,Kd),...
    @H, [t0 t1],x0);

yout = y(end,:);
end

